### ISSUE TITLE
[FEATURE] Add a section in the wadm manifest for scaler config

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#101]
Looking for comments and thoughts on this one, it's a half RFC.

When creating more complex wadm manifests, I noticed that I was often copying the same scaler config around for multiple resources. For example, if I wanted to have 3 actors all run on a host with a custom label, I'll have to add this for each actor:
```yaml
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: custom
                requirements:
                  app: custom
```

It could be nice to be able to define this as custom configuration with a name, and then re-use that config using that name later. Essentially, this would just ensure that I could define multiple components with the same traits with fewer lines. This could look like the following:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-backend
  annotations:
    version: v0.0.1
    description: "My Backend"
spec:
  traits:
    - type: spreadscaler
      name: customspreadscaler
      properties:
        replicas: 1
        spread:
          - name: custom
            requirements:
              app: custom
  components:
    - name: myactor1
      type: actor
      properties:
        image: ghcr.io/myactor:0.1.0
      traits:
        - name: customspreadscaler
    - name: myactor2
      type: actor
      properties:
        image: ghcr.io/myactor2:0.1.0
      traits:
        - name: customspreadscaler
```

This is just a thought and I'm happy to be challenged here, I worry about making it too confusing with jumping around to multiple places in a manifest to understand the spread configuration
