### ISSUE TITLE
[FEATURE] Support `config_json` for provider start commands

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#102]
Capability providers support an optional JSON configuration which we should be able to support via a `config` block in wadm. You can see the `configuration` variable in the interface: https://docs.rs/wasmcloud-interface-lattice-control/0.18.0/wasmcloud_interface_lattice_control/struct.StartProviderCommand.html. 

This is most useful for defining configuration that a provider will use for _every_ link, like a different default HTTPserver port with the wasmCloud httpserver provider. This `config` block would be taken and sent along to the start provider command. It would be nicer to specify nested config as YAML or JSON instead of just an opaque string, but the provider itself may or may not support a specific format

This would look something like this:
```
    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.17.0
        contract: wasmcloud:httpserver
        config: {"address": "0.0.0.0:8085"}
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
```

It would be important here to note the difference between provider configuration and the linkdef trait, since they can be used for different things.
