### ISSUE TITLE
[BUG] cannot recreate app name after all its versions have been deleted

### ISSUE THREAD

**Issue by pgray** [wasmCloud/wadm#129]
# Summary:
When you delete the last or only version of an app it seems to "burn" that app name such that all subsequent `wash app put` calls fail with `Internal storage error`

# Logs from `wadm`:
```
ERROR serve: wadm::server::handlers: Unable to store updated data error=Custom { kind: Other, error: "nats: error while pub       │ lishing message: 10071, 400, wrong last sequence: 8" }
```

# Steps to reproduce:
```
# cleanup local env
wash down --all && rm -rf $HOME/.wash && rm -rf /tmp/nats/*

# write simple echo.yml
cat <<EOF > echo.yml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: echo
  annotations:
    version: v0.0.1
    description: "This is my app"
spec:
  components:
    - name: echo
      type: actor
      properties:
        image: wasmcloud.azurecr.io/echo:0.3.7
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
EOF

# and repro
wash up -d && wash app put ./echo.yml && wash app del echo v0.0.1 && wash app put ./echo.yml
```
