### ISSUE TITLE
[BUG] wadm spreadscaler requirements don't work as numbers

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#131]
I defined a spreadscaler requirement as a number, like below.
```yaml
        spread:
          - name: myspread
            weight: 100
            requirements:
              host_number: 0
```

Unfortunately, it seems we can parse that number as a JSON value that's not a string, so even though my host had the label `host_number=0` it did not match the scaler property. The fix was as follows:
```yaml
        spread:
          - name: myspread
            weight: 100
            requirements:
              host_number: "0"
```

Because host labels are always interpreted as string:string maps, we should either enforce that in our parsing of the manifest or parse host labels as JSON values. I think the better solution is to keep it simple and parse spread key/value requirements as strings, but am open to other opinions as well.
