### ISSUE TITLE
[BUG] Newly deployed applications do not terminate old resources

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#145]
When you create a new version of an application, we create entirely new Spreadscaler instances that handle computing state and launching new resources according to the latest version. However, old resources that are no longer present aren't removed when upgrading the application. Consider the following manifest for KV counter:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kvcounter
  annotations:
    version: v0.0.1
    description: "wasmCloud Key Value Counter Example"
spec:
  components:
    - name: kvcounter
      type: actor
      properties:
        image: wasmcloud.azurecr.io/kvcounter:0.4.2
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: redis
            values:
              URL: redis://127.0.0.1:6379/
        - type: linkdef
          properties:
            target: httpserver
            values:
              ADDRESS: 0.0.0.0:8081

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.17.0
        contract: wasmcloud:httpserver
    - name: redis
      type: capability
      properties:
        image: wasmcloud.azurecr.io/kvredis:0.21.0
        contract: wasmcloud:keyvalue
```

Now, if I were to swap out my capability of redis for kv-vault for example,
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kvcounter
  annotations:
    version: v0.0.1
    description: "wasmCloud Key Value Counter Example"
spec:
  components:
    - name: kvcounter
      type: actor
      properties:
        image: wasmcloud.azurecr.io/kvcounter:0.4.2
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: vault
        - type: linkdef
          properties:
            target: httpserver
            values:
              ADDRESS: 0.0.0.0:8081

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.17.0
        contract: wasmcloud:httpserver
    - name: vault
      type: capability
      properties:
        image: wasmcloud.azurecr.io/kv-vault:0.4.1
        contract: wasmcloud:keyvalue
```

What I would expect to happen is
1. New manifest is deployed
2. Redis provider isn't present in manifest, so it's removed
3. Link definition to redis is deleted
4. KV vault provider is started
5. KV vault provider health check passes, link is put between kvcounter and vault

Steps 2 and 3 above are the new things that must be added to address this issue. I imagine the implementation of this will include adding some logic to compare the old application scalers to the new ones, and anything that's present in old that's not present in the new should be deleted. Note that scalers _can_ handle changing the amount of replicas of an actor or provider, it's just when you modify to use a different actor or provider (or version #143) that the issue comes into play.
