### ISSUE TITLE
[FEAT] Assign leftover instances by weight, instead of spread order

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#154]
### Summary
In the spreadscaler, the [compute_spread](https://github.com/wasmCloud/wadm/blob/main/src/scaler/spreadscaler/mod.rs#L345) function takes a spreadscaler configuration and returns a list of tuples of the spread and the total number of replicas to assign to that spread. This is generally pretty fair, taking into account weight and the requested number of replicas in order to fully spread that resource (actor or provider) across the different hosts.

### Current behavior
However, because of part of the algorithm, we end up slightly favoring spread requirements defined earlier in the YAML, rather than the ones with the highest weight. Consider this code, the first line calculates the number of replicas to assign to a spread and the second iteration will take the remaining replicas after that calculation and assign them in the order that the iter returns:
```rust
                // Order is important here since usizes chop off remaining decimals
                (replicas * s.weight.unwrap_or(DEFAULT_SPREAD_WEIGHT)) / total_weight,
/// elided
            // Take the remainder of replicas and evenly distribute among remaining spreads
            let mut diff = replicas - total_replicas;
            spreads
                .into_iter()
                .map(|(spread, count)| {
                    let additional = if diff > 0 {
                        diff -= 1;
                        1
                    } else {
                        0
                    };
                    (spread, count + additional)
                })
                .collect()
```

There's nothing wrong with this and, with the snippet after to assign leftover instances, this will always spread the replicas around properly. However, consider the following spread:
```yaml
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: eastcoast
                requirements:
                  zone: us-east-1
                weight: 20
              - name: westcoast
                requirements:
                  zone: us-west-1
                weight: 80
```

In this scenario, we want to run one instance of the resource with a 20% weight in east, and a 80% weight in west. Based on the current algorithm, we would assign `(1 * .20) / 1 = 0` replicas to the first, and `(1 * .8) / 1 = 0` replicas to the second. So, we'll have one leftover replica, which we will just assign to **eastcoast** because it comes first in the vector of spreads. It's also possible that the list isn't guaranteed to be sorted in that way, which would be worse as it leads to undetermined behavior.

### Expected behavior
The spread above should favor the **westcoast** spread requirement as it has a higher weight, and ignore the order of the YAML list. This is likely a simple change, simply sorting the spread requirements by weight before randomly assigning the remaining replicas.
