### ISSUE TITLE
[BUG] Validate that link definition values are string->string pairs

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#176]
wadm fails silently with the below link definition, when it should fail at `put` time.
```yaml
        - type: linkdef
          properties:
            target: http
            values:
              port: 8085
```

Instead, the proper manifest is 
```yaml
        - type: linkdef
          properties:
            target: http
            values:
              port: '8085'
```

This is a stance we took in #153 for spreadscaler requirements, but we didn't include link definition values in this. This is correct since [LinkSettings](https://docs.rs/wasmbus-rpc/0.14.0/wasmbus_rpc/core/type.LinkSettings.html) is a hashmap of string to string. If we wanted to try and deserialize values here as non-strings, we could, but then that might mess up downstream processing.

Looking back, I don't see the check to ensure spreadscaler requirements are string->string, @aish-where-ya am I missing that?
