### ISSUE TITLE
[FEAT] Support management of configuration in wadm apps

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#252]
With the changes to wadm for 1.0 in #247, we added the support for named configuration within wadm manifests. This currently only works if the configuration already exists, so effectively all values in the manifest are ignored. What we should have instead is the notion of a configuration scaler that is responsible for creating all the configuration specified in a manifest before starting the application components themselves.

Configuration can either be specified as a name, or as a name with values. If specified as a name with values, wadm should be responsible for creating that configuration and making sure it stays created.

We discussed offline, and the exact method is still up in the air, but it would be preferable to namespace the configuration based on the name of the application for better uniqueness. For example, a manifest like so:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kvcounter-rust
  annotations:
    version: v0.0.1
    description: "Kvcounter demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)"
    experimental: true
spec:
  components:
    - name: kvcounter
...
            target_config:
              - name: redis-connect-local
                properties:
                  url: redis://127.0.0.1:6379
```

We should create a configuration value with name `kvcounter-rust-redis-connect-local`. Since we're essentially concatenating strings together we shouldn't have an expectation to be able to find out the name of the config or the manifest name by splitting the string, but I'm not aware of a scenario where we'd need to do this in code. The reason this is important is to avoid different manifests from clashing with each other with similarly named config, e.g. something like `default-port`.
