### ISSUE TITLE
[FEAT] Support storing original YAML string for app

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#271]
Currently, when storing an application, wadm parses the YAML string into a manifest and stores the serialized version of that manifest. After validating that the manifest is in a proper shape, it would be great to store the entire original manifest string to preserve comments and the original form order.

For example, here's our HTTP hello world manifest:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-hello-world
  annotations:
    version: v0.0.1
    description: "HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)"
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file://./build/http_hello_world_s.wasm
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.20.0
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8080 for incoming requests
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
```

After deploying, if you were to retrieve the manifest it would look something like this:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-hello-world
  annotations:
    version: v0.0.1
    description: "HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)"
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file:///path/to/build/http_hello_world_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread: []

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.20.0
      traits:
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
```

Not only are comments removed, but some new fields are added (which we can compensate for by better serialization skips. I think primarily it would be great to keep comments after deployment to remember context.
