### ISSUE TITLE
[FEATURE]: Add regex matching to spreadscalers

### ISSUE THREAD

**Issue by jamesstocktonj1** [wasmCloud/wadm#419]
# Description
This feature lets you deploy to a set of labels which match the RegEx rather than just being equal to a label. This could allow for the following:
- may reduce the number of labels per-host
- keep traffic within a single availability zone (for use with Nats Leaf Nodes)
- should be backwards compatible (provided your label doesn't have \, *, + etc...)

## Example
Imagine a set of 5 nodes, each with the following `zone` labels:
- us-east-1
- us-east-2
- us-west-1
- us-west-2
- eu-west-1

And the following spreadscaler config:
```
- type: spreadscaler
  properties:
    replicas: 100
    spread:
      - name: spread-a
        requirements:
          zone: ([a-z]{2})-west-1
```

Would result in deployment to:
- us-west-1
- eu-west-1

This prevents the need for separate labels for country, region and availability zone.
