### ISSUE TITLE
[FEAT] Validate manifests to ensure links are unique

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#445]
As of wasmCloud v1.3.0, you cannot define links from the same source on the same namespace, package, and interface but to two different targets _without_ specifying a separate link name. This technically wasn't checked before in wasmCloud but it never worked for wasmCloud components, and only worked for capability providers because they are able to synthesize additional information in their implementations.

We need a validation rule to ensure that this is not possible when deploying a manifest, since it's just frustrating to have this pop up as an issue afterwards. In this validation rule, the following manifest should fail:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-link-name-uniqueness
  annotations:
    description: 'test'
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file://./build/http_hello_world_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
    - name: http-component-two
      type: component
      properties:
        image: file://./build/http_hello_world_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
        - type: link
          properties:
            target: http-component-two
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http-two
                properties:
                  address: 127.0.0.1:8081
```

Note that above the links are effectively identical, but with different targets and configuration. The correct traits block is as follows:
```yaml
      traits:
        - type: link
          properties:
            target: http-component
            name: default # for clarity, specifying "default" is the same as not specifying
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080
        - type: link
          properties:
            target: http-component-two
            name: link-two # can be named anything, but must not be "default"
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http-two
                properties:
                  address: 127.0.0.1:8081
```
