### ISSUE TITLE
[CHORE] Drop the `v` in front of the image tag

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#465]
We should publish container images without the `v` in version. E.g. today we publish `v0.18.0`, but we should publish just `0.18.0`.

For a few releases, we should make sure to publish both

**Comment by bp7968h** [comment]
@brooksmtownsend , can I work on this please, below is my solution, please do suggest me if there are better way of doing this:
```yml
- name: Build and push (tag)
        uses: docker/build-push-action@v6
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: ./
          build-args: |
            BIN_ARM64=./artifacts/wadm-${{ env.RELEASE_VERSION }}-linux-aarch64
            BIN_AMD64=./artifacts/wadm-${{ env.RELEASE_VERSION }}-linux-amd64
          tags: |
            ghcr.io/${{ env.OWNER }}/wadm:latest,
            ghcr.io/${{ env.OWNER }}/wadm:${{ env.RELEASE_VERSION }},
            ghcr.io/${{ env.OWNER }}/wadm:${{ env.RELEASE_VERSION#v }}
```

And can do the same for `wolfi` as well.
