### ISSUE TITLE
Shared providers can't use explicit IDs

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#474]
If I have a shared provider like the one in the example below that has an explicit ID, links do not work properly:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: shared-provider
  annotations:
    description: "Shared provider instances"
    experimental.wasmcloud.dev/shared: "true"
spec:
  components:
    - name: custom-provider
      type: capability
      properties:
        image: custom-provider:0.0.0
        id: custom-provider
      traits:
        - type: spreadscaler
          properties:
            instances: 1
```

If you look at the published linkdefs, you'll get a different source ID than you should when using it in another manifest:

```
❯ wash link get


  Source ID                          Target                                 Interface(s)              Name
  shared_provider-custom_provider   01914a67-f1c6-70e6-9ddd-e4f4437ee407   wasi:http/incoming-handler   default
```

This should be just a fix that checks if a target manifest has an ID and to use that instead of generating it.
