### ISSUE TITLE
[BUG] Unable to link to two target components that use different interfaces but the same namespace and package

### ISSUE THREAD

**Issue by LUK3ARK** [wasmCloud/wadm#514]
If i have 2 separate links from a component, with one needing to target a provider and one needing to target a component, Wadm only ever loads the first link and not the second. if i remove the first link, the second gets loaded. I am unable to get both loaded at the same time

```yaml
- name: my-component
  type: component
  traits:
    - type: link
      properties:
        target: data-component
        namespace: acme
        package: storage    # Same namespace/package
        interfaces: ["cache"]
    - type: link
      properties:
        target: data-provider
        namespace: acme
        package: storage    # Same namespace/package
        interfaces: ["query", "read", "other-interface"]  # Different interface
```

I expect when i run 'wash get links' to see both of these links, But only the first in the wadm file ever gets linked

wash          v0.36.1
├ nats-server v2.10.20
├ wadm        v0.18.0
└ wasmcloud   v1.4.0
