### ISSUE TITLE
[BUG] Linkdef scalers require values

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#96]
I tried to define a linkdef scaler with the following spec:
```yaml
        - type: linkdef
          properties:
            target: httpclient
```

It did not get put. But, when adding example values, it works
```yaml
        - type: linkdef
          properties:
            target: httpclient
            values:
              foo: bar
```

We should make this list optional
